### PR TITLE
Add Firefox updates for mitigating timing attacks

### PR DESCRIPTION
**Pull request by paulRbr**
Add links to current upgrade for Firefox thaht intends to mitigate risks of timing attack with Javascript.

### CODE REVIEW

**Comment by gvarisco** [comment]
Hey Paul, thanks! Are you sure Chrome has addressed it in 63.0.3239.132? I couldn't find much in the log they publish.

**Comment by paulRbr** [comment]
Hey @gvarisco wow indeed I can't find anything in the commits log. And from https://www.chromium.org/Home/chromium-security/ssca they announce a date of 23rd of Jan.

I'll remove the chrome update from the PR for now until we have further info.

**Comment by gvarisco** [comment]
Yeah, https://www.chromium.org/Home/chromium-security/ssca is what we can rely on until 23-24/01.

**Comment by paulRbr** [comment]
I've amended the commit.

**Review by gvarisco — APPROVED** [review]
LGTM

**Pull request merged**
