### PR TITLE
redhat check script

### PR DESCRIPTION
**Pull request by vsth**
Script shows up the vulnerable state for spectre variante #1 and #2 and also meltdown variants #3

### CODE REVIEW

**Comment by gvarisco** [comment]
404'ing for me. Is RHN login required? If yes, we should probably mention it.

**Comment by dhekimian** [comment]
From RedHat's KB Article https://access.redhat.com/security/vulnerabilities/speculativeexecution on the Diagnose Tab, is the link to the script. Its public and doesn't require a RHN login.

It looks like the script has been updated so the link might not work since they pulled it?

- v1.0 https://access.redhat.com/sites/default/files/spectre-meltdown--f79986c.sh
- v1.3 [Latest] https://access.redhat.com/sites/default/files/spectre-meltdown--a2f5749.sh

**Comment by cliffy94** [comment]
Quick comment, please use 'Red Hat', vs 'Redhat'. The company name is two separate words. Thanks!

**Comment by cliffy94** [comment]
I should also mention that the version of the script - will change over time - as such, so will the URL for direct download. It may be easier to state that this is available under the Diagnose tab of the main Red Hat Vulnerability article.

**Comment by vsth** [comment]
The script shows very nice whats happen if your rhel are updated but the hypervisor has not been updated.

**Comment by gvarisco** [comment]
Thank you, everyone! Merging.

**Pull request merged**
